#!/bin/bash

#PBS -V
#PBS -S /bin/bash
#PBS -N GRU
#PBS -l nodes=1:ppn=1
#PBS -l walltime=15:00:00
#PBS -M yss265@nuy.edu
#PBS -l mem=10GB
#PBS -q s48
#PBS -m bea
#PBS -e localhost:${PBS_O_WORKDIR}/log/${PBS_JOBNAME}.e${PBS_JOBID}
#PBS -o localhost:${PBS_O_WORKDIR}/log/${PBS_JOBNAME}.o${PBS_JOBID}

cd /scratch/yss265/DeepLearning/assignment4/lstm_me
module load torch
th mainGRU.lua --filePrefix GRU_
exit 0;
# th main.lua --dropout $drop --filePrefix $name --layers $layer
# exit 0;